from datetime import datetime


def create_report(title: str, summary: str, details: str = "", sources: list[str] | None = None):
    """Create a formatted text report."""

    date = datetime.now().strftime("%d %B %Y %I:%M %p")

    sources_text = "No sources available."

    if sources:
        sources_text = "\n".join(
            f"{i}. {source}"
            for i, source in enumerate(sources, start=1)
        )

    return f"""
==================================================
{title}
==================================================

Date: {date}

SUMMARY
--------------------------------------------------
{summary}

DETAILS
--------------------------------------------------
{details}

SOURCES
--------------------------------------------------
{sources_text}

==================================================
Generated by Office Assistant
==================================================
""".strip()