import asyncio
import json
from typing import Any


class TaskExecutor:

    def __init__(self, tools):

        self.tools = tools

        self.tool_map = {
            tool.name: tool
            for tool in tools
        }

    # =================================================
    # NORMALIZE LLM RESPONSE
    # =================================================

    def normalize_llm_content(self, content):

        if isinstance(content, list):

            text = ""

            for item in content:

                if isinstance(item, dict):

                    if item.get("type") == "text":

                        text += item.get(
                            "text",
                            ""
                        )

                else:

                    text += str(item)

            return text.strip()

        return str(content).strip()

    # =================================================
    # PARSE JSON
    # =================================================

    def parse_json_response(self, content):

        content = self.normalize_llm_content(
            content
        )

        if content.startswith("```"):

            content = content.replace(
                "```json",
                ""
            )

            content = content.replace(
                "```",
                ""
            )

            content = content.strip()

        return json.loads(content)

    # =================================================
    # FORMAT EMAIL BODY
    # =================================================

    def format_email_body(self, body):

        if not isinstance(body, str):

            return body

        lines = body.splitlines()

        cleaned_lines = []

        for line in lines:

            stripped = line.strip()

            # -----------------------------------------
            # Remove report separator lines
            # -----------------------------------------

            if stripped:

                if all(
                    character in "=- "
                    for character in stripped
                ):

                    continue

            # -----------------------------------------
            # Remove internal report footer
            # -----------------------------------------

            if (
                stripped.lower()
                == "generated by office assistant"
            ):

                continue

            # -----------------------------------------
            # Remove unnecessary report headings
            # -----------------------------------------

            if stripped.upper() == "SOURCES":

                continue

            cleaned_lines.append(line)

        body = "\n".join(
            cleaned_lines
        )

        # ---------------------------------------------
        # Remove excessive blank lines
        # ---------------------------------------------

        while "\n\n\n" in body:

            body = body.replace(
                "\n\n\n",
                "\n\n"
            )

        return body.strip()

    # =================================================
    # RISK ANALYSIS
    # =================================================

    async def analyze_risk(
        self,
        tool_name: str,
        arguments: dict,
    ):

        from app.agent import llm, build_prompt_messages

        prompt = f"""
You are a security and authorization evaluator.

Tool:
{tool_name}

Arguments:
{json.dumps(arguments, indent=2, default=str)}

Determine whether this operation requires
human approval.

HIGH risk:
- sends email or external communication
- deletes data
- modifies important records
- causes financial consequences
- performs an irreversible external action

MEDIUM risk:
- modifies data but has limited consequences

LOW risk:
- read-only lookup
- search
- listing files
- retrieving weather
- calculating information
- checking status
- generating a local report

IMPORTANT SECURITY RULE:

Any operation that sends an external email MUST
be classified as HIGH risk and MUST require
human approval.

IMPORTANT:

Risk must be determined primarily by WHAT THE TOOL
DOES, not merely by the sensitivity of information
contained in the arguments.

For example:

generate_report_tool
= local report generation
= LOW risk

send_a_email
= external communication
= HIGH risk

Return ONLY valid JSON.

{{
    "risk": "LOW",
    "requires_approval": false,
    "reason": "Short explanation"
}}
"""

        response = await llm.ainvoke(
            build_prompt_messages(prompt)
        )

        content = self.normalize_llm_content(
            response.content
        )

        try:

            result = self.parse_json_response(
                content
            )

            # -----------------------------------------
            # SECURITY OVERRIDES
            # -----------------------------------------

            # =================================================
            # EMAIL
            # =================================================

            if tool_name == "send_a_email":

                result["risk"] = "HIGH"

                result[
                    "requires_approval"
                ] = True

                result["reason"] = (
                    "Sending an external email is "
                    "an external communication and "
                    "requires human approval."
                )

            # =================================================
            # REPORT GENERATION
            # =================================================

            elif tool_name == "generate_report_tool":

                result["risk"] = "LOW"

                result[
                    "requires_approval"
                ] = False

                result["reason"] = (
                    "Local report generation does not "
                    "modify data, send external "
                    "communication, or perform an "
                    "irreversible action."
                )

            return result

        except Exception:

            # -----------------------------------------
            # Safe fallback
            # -----------------------------------------

            if tool_name == "generate_report_tool":

                return {

                    "risk": "LOW",

                    "requires_approval": False,

                    "reason": (
                        "Local report generation does "
                        "not perform an external action."
                    ),
                }

            return {

                "risk": "HIGH",

                "requires_approval": True,

                "reason": (
                    "Risk analysis could not be "
                    "parsed safely."
                ),
            }

    # =================================================
    # CHECK FOR TASK REFERENCE
    # =================================================

    def contains_task_reference(
        self,
        value
    ):

        if isinstance(value, str):

            return (
                "{{FROM_TASK:" in value
                or "{FROM_TASK:" in value
            )

        if isinstance(value, dict):

            return any(
                self.contains_task_reference(
                    item
                )
                for item in value.values()
            )

        if isinstance(value, list):

            return any(
                self.contains_task_reference(
                    item
                )
                for item in value
            )

        return False

    # =================================================
    # GET TASK REFERENCES
    # =================================================

    def get_task_references(
        self,
        value
    ):

        references = []

        if isinstance(value, str):

            import re

            # -----------------------------------------
            # Standard format:
            # {{FROM_TASK:task_1}}
            # -----------------------------------------

            pattern = r'\{\{FROM_TASK:([^}]+)\}\}'

            matches = re.findall(
                pattern,
                value
            )

            references.extend(
                matches
            )

            # -----------------------------------------
            # Also support:
            # {FROM_TASK:task_1}
            # -----------------------------------------

            pattern = r'\{FROM_TASK:([^}]+)\}'

            matches = re.findall(
                pattern,
                value
            )

            for match in matches:

                if match not in references:

                    references.append(
                        match
                    )

        elif isinstance(value, dict):

            for item in value.values():

                references.extend(
                    self.get_task_references(
                        item
                    )
                )

        elif isinstance(value, list):

            for item in value:

                references.extend(
                    self.get_task_references(
                        item
                    )
                )

        return references

    # =================================================
    # GET TOOL SCHEMA
    # =================================================

    def get_tool_schema(
        self,
        tool
    ):

        tool_schema = {}

        try:

            if (
                hasattr(
                    tool,
                    "args_schema"
                )
                and tool.args_schema
            ):

                if hasattr(
                    tool.args_schema,
                    "model_json_schema"
                ):

                    tool_schema = (
                        tool.args_schema
                        .model_json_schema()
                    )

                elif hasattr(
                    tool.args_schema,
                    "schema"
                ):

                    tool_schema = (
                        tool.args_schema.schema()
                    )

        except Exception:

            tool_schema = {}

        return tool_schema

    # =================================================
    # PREPARE DEPENDENT ARGUMENTS USING LLM
    # =================================================

    async def prepare_arguments_with_llm(
        self,
        tool,
        arguments,
        task_results,
    ):

        from app.agent import llm, build_prompt_messages

        # =================================================
        # NO DEPENDENCY
        # =================================================

        if not self.contains_task_reference(
            arguments
        ):

            print(
                "\nℹ️ No task dependency found."
            )

            return arguments

        # =================================================
        # FIND REFERENCED TASKS
        # =================================================

        referenced_tasks = (
            self.get_task_references(
                arguments
            )
        )

        print(
            "\n🔗 Task dependencies detected:"
        )

        for task_id in referenced_tasks:

            print(
                f"   → {task_id}"
            )

        # =================================================
        # COLLECT PREVIOUS RESULTS
        # =================================================

        previous_data = {}

        for task_id in referenced_tasks:

            if task_id not in task_results:

                raise RuntimeError(
                    f"Required task result "
                    f"'{task_id}' was not found."
                )

            previous_data[
                task_id
            ] = task_results[
                task_id
            ]

        print(
            "\n📦 PREVIOUS TASK DATA"
        )

        print(
            json.dumps(
                previous_data,
                indent=2,
                default=str
            )
        )

        # =================================================
        # TOOL INFORMATION
        # =================================================

        tool_name = tool.name

        tool_description = (
            tool.description
            or ""
        )

        tool_schema = (
            self.get_tool_schema(
                tool
            )
        )

        # =================================================
        # LLM PROMPT
        # =================================================

        prompt = f"""
You are an argument preparation assistant.

You are preparing the FINAL arguments for an MCP tool.

The current tool depends on the result of ONE OR MORE
previous tasks (multi-source dependency - Approach 2).

Your job is to convert the previous task results into
the correct final arguments for the current tool.

IMPORTANT: This workflow involves multiple data sources.

DO NOT execute the tool.

DO NOT invent information.

DO NOT leave any FROM_TASK placeholder.

Every placeholder MUST be replaced with real
information from the previous task results.

--------------------------------------------------
TARGET TOOL
--------------------------------------------------

Name:
{tool_name}

Description:
{tool_description}

Schema:
{json.dumps(tool_schema, indent=2, default=str)}

--------------------------------------------------
CURRENT ARGUMENTS (WITH PLACEHOLDERS)
--------------------------------------------------

{json.dumps(arguments, indent=2, default=str)}

--------------------------------------------------
PREVIOUS TASK RESULTS (MULTIPLE SOURCES)
--------------------------------------------------

{json.dumps(previous_data, indent=2, default=str)}

--------------------------------------------------
IMPORTANT RULES
--------------------------------------------------

1. Preserve all arguments that are already known.

2. Replace every:

   {{FROM_TASK:task_id}}

   with useful information from that task.

3. NEVER return a FROM_TASK placeholder.

4. NEVER mention task IDs in the final output.

5. NEVER mention MCP.

6. NEVER mention LangGraph.

7. NEVER mention this prompt.

8. Do not invent facts.

9. MULTI-SOURCE HANDLING:

   When combining multiple task results:

   - Understand all data sources
   - Organize them logically
   - Create clear section headers for each source
   - Use consistent formatting
   - Ensure information flows naturally

10. If the target tool is a REPORT GENERATOR:

    - Create a well-structured report
    - Include a clear title
    - Provide a summary section
    - Organize details into logical sections
    - Use section headers for each data source
    - Format numbers with commas and decimals
    - Include dates if available
    - Make it professional and readable

11. If the target tool is an EMAIL TOOL:

    - Keep the "to" address unchanged
    - Create a meaningful subject
    - Create a professional email body
    - Include all useful information from previous tasks
    - Convert report-style information into natural email format
    - Use clear section headings
    - Use readable spacing
    - DO NOT copy raw report formatting
    - DO NOT copy lines made of "="
    - DO NOT copy lines made of "-"
    - DO NOT include "Generated by Office Assistant"
    - DO NOT include unnecessary internal report headers
    - DO NOT include internal task information
    - DO NOT mention task IDs
    - DO NOT mention MCP
    - DO NOT mention LangGraph

12. If a previous result is structured data (JSON object):

    - Extract relevant fields
    - Format them in a readable way
    - Use proper labels for each field

13. If a previous result is a web search:

    - Summarize the useful information
    - Organize by relevance

14. If a previous result is weather data:

    - Create a readable weather summary
    - Include temperature, condition, humidity
    - Format clearly with section headers

15. If a previous result is an employee record:

    - Format employee information clearly
    - Include ID, name, department, salary
    - Use comma separators for financial values

16. If the previous result is a report object:

    - Extract the text content
    - Reformat it appropriately for the target tool
    - Maintain key information while improving readability

17. The solution must work generically for ANY
    previous task results.

18. For salary or monetary values:

    - use comma separators
    - use two decimal places when appropriate

    Example:

    50000.0 → 50,000.00

--------------------------------------------------
MULTI-SOURCE PROFESSIONAL FORMAT EXAMPLE
--------------------------------------------------

If combining employee data, weather, and budget:

REPORT VERSION:

Title: Complete Employee & Department Overview

Summary:
Consolidated information for Employee 1 including
environmental conditions and departmental budget status.

Employee Details
---------------

Employee ID: 1
Name: John Doe
Department: IT
Salary: 75,000.00

Weather Information — Valsad
----------------------------

Current Condition: Sunny
Temperature: 28.5°C
Humidity: 65%

Department Budget — IT
---------------------

Total Budget: 500,000.00
Amount Spent: 250,000.00
Remaining: 250,000.00


EMAIL VERSION:

Hello,

Please find below the consolidated information requested.

Employee Details

Employee 1 is John Doe from the IT department with
an annual salary of 75,000.00.

Weather Update — Valsad

The current weather in Valsad is sunny with a
temperature of 28.5°C and humidity at 65%.

Budget Status — IT Department

The IT department has a total budget of 500,000.00,
with 250,000.00 spent to date and 250,000.00 remaining.

Best regards,
Office Assistant

--------------------------------------------------
FINAL REQUIREMENT
--------------------------------------------------

Return ONLY a valid JSON object.

Do not return markdown.

Do not return ```json.

Do not return explanations.
"""

        # =================================================
        # CALL LLM
        # =================================================

        response = await llm.ainvoke(
            build_prompt_messages(prompt)
        )

        content = self.normalize_llm_content(
            response.content
        )

        print(
            "\n🧠 LLM DEPENDENCY RESPONSE"
        )

        print(
            content
        )

        # =================================================
        # PARSE RESPONSE
        # =================================================

        try:

            prepared_arguments = (
                self.parse_json_response(
                    content
                )
            )

            if not isinstance(
                prepared_arguments,
                dict
            ):

                raise ValueError(
                    "LLM returned non-object arguments."
                )

        except Exception as e:

            print(
                "\n❌ Failed to prepare "
                "dependent arguments."
            )

            print(
                f"Reason: {e}"
            )

            raise RuntimeError(
                "The AI could not safely prepare "
                "the arguments for the dependent task."
            )

        # =================================================
        # FINAL PLACEHOLDER CHECK
        # =================================================

        if self.contains_task_reference(
            prepared_arguments
        ):

            print(
                "\n❌ LLM left an unresolved "
                "FROM_TASK placeholder."
            )

            print(
                json.dumps(
                    prepared_arguments,
                    indent=2,
                    default=str
                )
            )

            raise RuntimeError(
                "The AI returned unresolved "
                "task references."
            )

        # =================================================
        # DISPLAY FINAL ARGUMENTS
        # =================================================

        print(
            "\n📤 FINAL TOOL ARGUMENTS"
        )

        print(
            json.dumps(
                prepared_arguments,
                indent=2,
                default=str
            )
        )

        return prepared_arguments

    # =================================================
    # BUILD APPROVAL INFORMATION
    # =================================================
    #
    # IMPORTANT:
    #
    # This creates UI-friendly approval metadata.
    #
    # It DOES NOT modify the actual MCP arguments.
    #
    # MCP still receives:
    #
    #     to
    #     subject
    #     body
    #
    # "recipient", "information", and "warning"
    # are only used by the approval/UI layer.
    #
    # =================================================

    def build_approval_metadata(
        self,
        tool_name: str,
        arguments: dict,
    ):

        metadata = {}

        # =================================================
        # EMAIL APPROVAL METADATA
        # =================================================

        if tool_name == "send_a_email":

            metadata = {

                # -----------------------------------------
                # UI DISPLAY ONLY
                # -----------------------------------------

                "recipient": arguments.get(
                    "to"
                ),

                "subject": arguments.get(
                    "subject"
                ),

                "information": arguments.get(
                    "body"
                ),

                "warning": (
                    "This action will send "
                    "information outside the system "
                    "and cannot be automatically undone."
                ),
            }

        return metadata

    # =================================================
    # EXECUTE SINGLE TASK
    # =================================================

    async def execute_task(
        self,
        task: dict,
        task_results: dict[str, Any],
        approved_tasks: set[str],
    ):

        task_id = task["id"]

        tool_name = task["tool"]

        original_arguments = task.get(
            "arguments",
            {}
        )

        # =================================================
        # FIND TOOL
        # =================================================

        tool = self.tool_map.get(
            tool_name
        )

        if tool is None:

            return {

                "task_id": task_id,

                "result": {

                    "success": False,

                    "tool": tool_name,

                    "error": (
                        f"Tool '{tool_name}' "
                        "not found."
                    ),
                },

                "pending_approval": None,
            }

        # =================================================
        # PREPARE FINAL ARGUMENTS
        # =================================================

        try:

            arguments = (
                await self.prepare_arguments_with_llm(
                    tool,
                    original_arguments,
                    task_results,
                )
            )

            # =================================================
            # CLEAN EMAIL BODY
            # =================================================

            if (
                tool_name == "send_a_email"
                and isinstance(arguments, dict)
                and "body" in arguments
            ):

                arguments["body"] = (
                    self.format_email_body(
                        arguments["body"]
                    )
                )

        except Exception as e:

            print(
                f"\n❌ Could not prepare task: "
                f"{task_id} → {tool_name}"
            )

            print(
                f"Reason: {e}"
            )

            return {

                "task_id": task_id,

                "result": {

                    "success": False,

                    "tool": tool_name,

                    "error": str(e),
                },

                "pending_approval": None,
            }

        # =================================================
        # FINAL SAFETY CHECK
        # =================================================

        if self.contains_task_reference(
            arguments
        ):

            print(
                "\n❌ SECURITY BLOCK"
            )

            print(
                "Unresolved FROM_TASK reference "
                "detected in final arguments."
            )

            return {

                "task_id": task_id,

                "result": {

                    "success": False,

                    "tool": tool_name,

                    "error": (
                        "Tool arguments contain "
                        "an unresolved task reference."
                    ),
                },

                "pending_approval": None,
            }

        # =================================================
        # START TASK
        # =================================================

        print(
            f"\n🚀 Starting task: "
            f"{task_id} → {tool_name}"
        )

        # =================================================
        # RISK ANALYSIS
        # =================================================

        risk_result = await self.analyze_risk(
            tool_name,
            arguments
        )

        risk = risk_result.get(
            "risk",
            "HIGH"
        )

        reason = risk_result.get(
            "reason",
            "Risk analysis unavailable."
        )

        requires_approval = risk_result.get(
            "requires_approval",
            True
        )

        print(
            f"\n🔍 Risk Analysis: {risk}"
        )

        print(
            f"Reason: {reason}"
        )

        # =================================================
        # HUMAN APPROVAL
        # =================================================

        if (
            requires_approval
            and task_id not in approved_tasks
        ):

            print(
                f"\n⏸️ Task paused for approval: "
                f"{task_id} → {tool_name}"
            )

            # =================================================
            # BUILD UI METADATA
            # =================================================
            #
            # IMPORTANT:
            #
            # This does NOT modify "arguments".
            #
            # The original MCP arguments remain:
            #
            # {
            #     "to": "...",
            #     "subject": "...",
            #     "body": "..."
            # }
            #
            # =================================================

            approval_metadata = (
                self.build_approval_metadata(
                    tool_name,
                    arguments,
                )
            )

            return {

                "task_id": task_id,

                "result": None,

                "pending_approval": {

                    "task_id": task_id,

                    # -----------------------------------------
                    # INTERNAL TOOL INFORMATION
                    # -----------------------------------------

                    "tool": tool_name,

                    # -----------------------------------------
                    # ACTUAL MCP ARGUMENTS
                    #
                    # DO NOT rename "to" here.
                    # -----------------------------------------

                    "arguments": arguments,

                    # -----------------------------------------
                    # RISK INFORMATION
                    # -----------------------------------------

                    "risk": risk,

                    "reason": reason,

                    "message": (
                        "This operation requires "
                        "your confirmation before "
                        "it can continue."
                    ),

                    # -----------------------------------------
                    # UI-FRIENDLY APPROVAL METADATA
                    #
                    # These are NOT sent to MCP.
                    # -----------------------------------------

                    **approval_metadata,
                },
            }

        # =================================================
        # EXECUTE TOOL
        # =================================================

        print(
            f"\n🔧 Running tool: "
            f"{tool_name}"
        )

        try:

            # =================================================
            # IMPORTANT MCP CONTRACT
            # =================================================
            #
            # The actual arguments are passed unchanged.
            #
            # For send_a_email:
            #
            # arguments =
            # {
            #     "to": "...",
            #     "subject": "...",
            #     "body": "..."
            # }
            #
            # We NEVER pass "recipient" to MCP.
            #
            # =================================================

            result = await tool.ainvoke(
                arguments
            )

            print(
                f"✅ Finished task: "
                f"{task_id} → {tool_name}"
            )

            return {

                "task_id": task_id,

                "result": {

                    "success": True,

                    "tool": tool_name,

                    "result": result,
                },

                "pending_approval": None,
            }

        except Exception as e:

            print(
                f"\n❌ Task failed: "
                f"{task_id} → {tool_name}"
            )

            print(
                f"Reason: {e}"
            )

            return {

                "task_id": task_id,

                "result": {

                    "success": False,

                    "tool": tool_name,

                    "error": str(e),
                },

                "pending_approval": None,
            }

    # =================================================
    # EXECUTE PLAN
    # =================================================

    async def execute_plan(
        self,
        execution_plan,
        previous_results=None,
        previous_approved=None,
        approved_tasks=None,
    ):

        # =================================================
        # SUPPORT BOTH PARAMETER NAMES
        # =================================================

        if previous_approved is None:

            previous_approved = (
                approved_tasks
                or []
            )

        # =================================================
        # RESTORE PREVIOUS RESULTS
        # =================================================

        task_results = dict(
            previous_results
            or {}
        )

        # =================================================
        # RESTORE APPROVED TASKS
        # =================================================

        approved_task_set = set(
            previous_approved
        )

        # =================================================
        # DEBUG
        # =================================================

        print(
            "\n📦 Previously completed tasks:"
        )

        if task_results:

            for task_id in task_results:

                print(
                    f"   ✓ {task_id}"
                )

        else:

            print(
                "   None"
            )

        print(
            "\n🔐 Previously approved tasks:"
        )

        if approved_task_set:

            for task_id in approved_task_set:

                print(
                    f"   ✓ {task_id}"
                )

        else:

            print(
                "   None"
            )

        # =================================================
        # ONLY INCOMPLETE TASKS
        # =================================================

        remaining = [

            task

            for task in execution_plan

            if task["id"]
            not in task_results
        ]

        print(
            "\n📋 Remaining tasks:"
        )

        if remaining:

            for task in remaining:

                print(
                    f"   → {task['id']} "
                    f"→ {task['tool']}"
                )

        else:

            print(
                "   None"
            )

        # =================================================
        # EXECUTION WAVES
        # =================================================

        while remaining:

            ready_tasks = []

            waiting_tasks = []

            # =================================================
            # FIND READY TASKS
            # =================================================

            for task in remaining:

                dependencies = task.get(
                    "depends_on",
                    []
                )

                if all(
                    dependency in task_results
                    for dependency in dependencies
                ):

                    ready_tasks.append(
                        task
                    )

                else:

                    waiting_tasks.append(
                        task
                    )

            # =================================================
            # DEADLOCK PROTECTION
            # =================================================

            if not ready_tasks:

                raise RuntimeError(
                    "Execution plan contains "
                    "unresolvable dependencies."
                )

            print(
                f"\n⚡ Running "
                f"{len(ready_tasks)} "
                f"task(s) in parallel..."
            )

            # =================================================
            # EXECUTE READY TASKS
            # =================================================

            results = await asyncio.gather(

                *[
                    self.execute_task(
                        task,
                        task_results,
                        approved_task_set,
                    )

                    for task in ready_tasks
                ]
            )

            # =================================================
            # FIND APPROVAL REQUEST
            # =================================================

            pending_request = None

            for execution_result in results:

                if (
                    execution_result.get(
                        "pending_approval"
                    )
                    is not None
                ):

                    pending_request = (
                        execution_result[
                            "pending_approval"
                        ]
                    )

                    break

            # =================================================
            # STORE COMPLETED RESULTS
            # =================================================

            for execution_result in results:

                task_id = execution_result[
                    "task_id"
                ]

                result = execution_result[
                    "result"
                ]

                if result is not None:

                    task_results[
                        task_id
                    ] = result

            # =================================================
            # STOP FOR APPROVAL
            # =================================================

            if pending_request is not None:

                print(
                    "\n⏸️ EXECUTION PAUSED"
                )

                print(
                    "Completed before approval:"
                )

                for task_id in task_results:

                    print(
                        f"   ✓ {task_id}"
                    )

                print(
                    "\nWaiting for approval:"
                )

                print(
                    f"   ⏸️ "
                    f"{pending_request['task_id']} "
                    f"→ "
                    f"{pending_request['tool']}"
                )

                return {

                    "task_results": task_results,

                    "approved_tasks": list(
                        approved_task_set
                    ),

                    "pending_approval": (
                        pending_request
                    ),

                    "execution_complete": False,
                }

            # =================================================
            # COMPLETED TASK IDS
            # =================================================

            completed_ids = {

                execution_result[
                    "task_id"
                ]

                for execution_result in results

                if execution_result.get(
                    "result"
                ) is not None
            }

            # =================================================
            # NEXT WAVE
            # =================================================

            remaining = [

                task

                for task in waiting_tasks

                if task["id"]
                not in completed_ids
            ]

        # =================================================
        # ALL TASKS COMPLETED
        # =================================================

        print(
            "\n📦 ALL TASKS COMPLETED"
        )

        return {

            "task_results": task_results,

            "approved_tasks": list(
                approved_task_set
            ),

            "pending_approval": None,

            "execution_complete": True,
        }